[versions]
### Core
coreKtxVersion = "1.17.0"
lifecycleRuntimeKtxVersion = "2.9.2"
activityComposeVersion = "1.10.1"

### Compose BOM
composeBomVersion = "2024.09.00"

### Room
mediaVersion = "1.7.0"
roomRuntimeVersion = "2.8.0"

### Hilt
hiltVersion = "2.49"
hiltNavigationVersion = "1.2.0"

### Navigation
navVersion = "2.7.7"

### Parsers
jsoupVersion = "1.18.3"
serializationVersion = "1.8.1"
storageVersion = "2.0.0"

### Tests
junitVersion = "4.13.2"

###

agpVersion = "8.10.1"
kotlinVersion = "2.0.21"
kspVersion = "2.0.21-1.0.25"

[libraries]
### Media
androidx-media = { module = "androidx.media:media", version.ref = "mediaVersion" }

### Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }

### Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.0" }

### Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntimeVersion" }

### Hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion" }
hilt-nav-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationVersion" }

### Navigation
nav-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion" }

### Parsers
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoupVersion" }
serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serializationVersion" }
storage = { group = "com.anggrayudi", name = "storage", version.ref = "storageVersion" }

### Tests
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agpVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }

